<?php

/**
 * @file themefeature.module
 * Theme Features
 */

/**
 * Implementation of hook_init
 */
function themefeature_init() {
  $check = cache_get("themefeature:done");
  if (!$check) {
    module_load_include("inc", "features", "features.export");
    $enabled = features_get_default_map("cssjs");
    foreach($enabled as $k => $v) {
    }
    cache_set("themefeature:done", time());
  }
}

/**
 * Implementation of hook_features_api
 */
function themefeature_features_api() {
  return array(
    'cssjs' => array(
      'file' => drupal_get_path("module", "themefeature") . '/includes/themefeature.cssjs.inc',
      'name' => 'CSS/JS components',
      'default_hook' => 'cssjs_defaults',
      'default_file' => FEATURES_DEFAULTS_INCLUDED_COMMON,
      'features_source' => TRUE,
    ),
  );
}

/**
 * Implementation of hook_features_export_alter
 */
function themefeature_features_export_alter(&$export, $module_name) {
}

