<?php

/**
 * @file themefeature.module
 * Theme Features
 */

/**
 * Implementation of hook_perm
 */
function themefeature_perm() {
  return array('prepare theme features');
}

/**
 * Implementation of hook_menu
 */
function themefeature_menu() {
  $items['admin/build/features/themefeature'] = array(
    'title' => t('Theme features'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('themefeature_admin_prepare'),
    'access arguments' => array('prepare theme features'),
    'file' => 'includes/themefeature.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function themefeature_help($section) {
  switch($section) {
    case 'admin/help#features':
      return "Theme Feature helps you turn theme files into features.";
    case 'admin/build/features/themefeature':
      return "Theme Feature can turn existing theme CSS and Javascript files into feature components by naming them below. These can then be packaged up into features.";
  }
}

/**
 * Implementation of hook_init
 */
function themefeature_init() {
  $dir = file_directory_path() . '/themefeature';

  // Re-create when cache is cleared
  $check = cache_get("themefeature:done");

  // Hack to get admin/build/modules and admin/build/features to react quickly
  (arg(0) == "admin") && (arg(1) == "build") && ($check = FALSE);

  if (!$check) {
    module_load_include("inc", "themefeature", "includes/themefeature.files");
    _themefeature_cache_recreate($dir);

    // We're done - let's not do this again!
    cache_set("themefeature:done", time());
  }

  // Now add any JS/CSS we can find in that directory
  foreach(glob("$dir/*.js") as $file) {
    drupal_add_js($file);
  }
  foreach(glob("$dir/*.css") as $file) {
    drupal_add_css($file);
  }
}

/**
 * Implementation of hook_features_api
 */
function themefeature_features_api() {
  return array(
    'cssjs' => array(
      'file' => drupal_get_path("module", "themefeature") . '/includes/themefeature.cssjs.inc',
      'name' => 'CSS/JS components',
      'default_hook' => 'cssjs_defaults',
      'default_file' => FEATURES_DEFAULTS_INCLUDED_COMMON,
      'features_source' => TRUE,
    ),
  );
}

/**
 * Implementation of hook_features_export_alter
 */
function themefeature_features_export_alter(&$export, $module_name) {
  // CSSJS features only work with the Theme Features module
  $export['features']['cssjs'] && ($export['dependencies']['themefeature'] = 'themefeature');
}

