<?php

/**
 * @file themefeature.module
 * Theme Features
 */

/**
 * Implementation of hook_init
 */
function themefeature_init() {
  $dir = variable_get('file_directory_path', 'files') . '/themefeature';

  // Re-create when cache is cleared
  $check = cache_get("themefeature:done");
  if (!$check) {
    module_load_include("inc", "themefeature", "includes/themefeature.cache");
    _themefeature_cache_recreate($dir);

    // We're done - let's not do this again!
    cache_set("themefeature:done", time());
  }

  // Now add any JS/CSS we can find
  foreach(glob("$dir/*.js") as $file) {
    drupal_add_js($file);
  }
  foreach(glob("$dir/*.css") as $file) {
    drupal_add_css($file);
  }
}

/**
 * Implementation of hook_features_api
 */
function themefeature_features_api() {
  return array(
    'cssjs' => array(
      'file' => drupal_get_path("module", "themefeature") . '/includes/themefeature.cssjs.inc',
      'name' => 'CSS/JS components',
      'default_hook' => 'cssjs_defaults',
      'default_file' => FEATURES_DEFAULTS_INCLUDED_COMMON,
      'features_source' => TRUE,
    ),
  );
}

/**
 * Implementation of hook_features_export_alter
 */
function themefeature_features_export_alter(&$export, $module_name) {
  // CSSJS features only work with the Theme Features module
  $export['features']['cssjs'] && ($export['dependencies']['themefeature'] = 'themefeature');
}

